### ISSUE TITLE
ssh into postgres container ?

### ISSUE THREAD

**Issue by hopewise** [luizkowalski/devcontainer-rails#5]
Hello

Thanks for this very handy repo! 

As I am new to Codespace, I need to ssh into the Postgres service and from there to import my DB sql file so that I can start development, but I noticed docker it self is not installed, I am wondering actually how docker-compose will work?

**Comment by luizkowalski** [comment]
hey @hopewise 👋🏻 

you don't really need to ssh into the PostgreSQL container actually. There are two ways you can do this:

a) you can update `boot.sh` script to import your SQL file using `psql ..` command
b) the Postgresql container is exposed locally via port 5433 as per documentation. you can use `psql ...` from your machine and do it

let me know how this works for you

**Comment by hopewise** [comment]
Thanks @luizkowalski , I tried b), but I got error

```
$ psql

psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
```

**Comment by luizkowalski** [comment]
you need to specify the port too. your error message is saying it is trying to connect on port 5432

**Comment by hopewise** [comment]
even if I explicitly set port number:

```
$ psql -p 5433
psql: error: connection to server on socket "/var/run/postgresql/.s.PGSQL.5433" failed: No such file or directory
        Is the server running locally and accepting connections on that socket?
```

**Comment by luizkowalski** [comment]
hmm that makes sense, it is trying to connect to the local socket. 
anyway, check the [psql documentation](https://www.postgresql.org/docs/current/app-psql.html), I think there are options to get around this, might work with `psql postgresql://localhost:5433/mydb`, according to the docs

I will go ahead and close this once since it can't be done from the container itself

**Comment by hopewise** [comment]
```
psql postgresql://localhost:5433/mydb
psql: error: connection to server at "localhost" (127.0.0.1), port 5433 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5433 failed: Cannot assign requested address
        Is the server running on that host and accepting TCP/IP connections?
        
#trying service name postgres:


psql postgresql://postgres:5433/mydb 
psql: error: connection to server at "postgres" (172.18.0.3), port 5433 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
        
                
```

**Comment by luizkowalski** [comment]
hey @hopewise 

sorry to hear it didn't work.

I'm not sure how you can do that, try option a) then. I've never had to do something like that before so you are in uncharted waters here hahahaha

**Comment by hopewise** [comment]
no worries! thank you very much,
