### ISSUE TITLE
Awesome project + install rails?

### ISSUE THREAD

**Issue by misner** [luizkowalski/devcontainer-rails#7]
Hi

Given the fact I've been struggling for days to have a working codespace for Ruby on rails, thnaks for your awesome initiative.

I was wondering. you mention "I've been trying to get some Ruby on Rails projects"=> but I don't see anywhere you installing Rails itself.

Am I missing sth?
Many thanks

**Comment by luizkowalski** [comment]
hey!

this template should be used on an existing Rails project. I guess what you actually want is to install Ruby and Rails and start a new project?
